server:
  port: 8888
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xpotify
    username: root
    password: lovecan148

#file config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: off

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1032386297814-16cbeoo78e8l5fbkuodqi8mdkt9a56ao.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          facebook:
            clientId: 278795124416403
            clientSecret: dda90f3692df9cbadd1fe14b9c6154b6

paypal:
  mode: sandbox
  client:
    id: AVGLJsptYsH2DFxUkYMiVNIbnwFuZPXvmfB_LoyTkF3HwDSX4pN8CS0quA7O2qoR1loJGc5tZsbQ3Zcf
    secret: EG5hrjE8yCh_1CpumrO2Zdegiz_QyzC1Z01U72GNBCz45jc22XRkOdEaA7tb_FYCeuejb1h5WNx5tyOP

logging:
  file.name: logs/xpotify-debug.log
  pattern:
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: ERROR
    org.springframework.security: INFO
    org.hibernate: ERROR
    com.xpotify: DEBUG

